"""Descripción de los cambios

Revision ID: ae64b826a42f
Revises: 
Create Date: 2026-05-11 12:43:26.933196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae64b826a42f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'image_url')
    op.drop_column('lessons', 'recursos_pdf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('recursos_pdf', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
