"""Add order and is_cover to CourseImage

Revision ID: c19679b29f7e
Revises: 006447d80a36
Create Date: 2026-05-19 10:27:13.279493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19679b29f7e'
down_revision: Union[str, Sequence[str], None] = '006447d80a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_images', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('course_images', sa.Column('is_cover', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_images', 'is_cover')
    op.drop_column('course_images', 'order')
    # ### end Alembic commands ###
