"""Add informative section fields to homeconfig

Revision ID: d3989c8a0604
Revises: f7d14fa01201
Create Date: 2026-08-05 17:41:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3989c8a0604'
down_revision: Union[str, Sequence[str], None] = 'f7d14fa01201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_configs', sa.Column('informative_title', sa.String(), nullable=False, server_default='CLASES PRESENCIALES Y ACTIVIDADES'))
    op.add_column('home_configs', sa.Column('informative_subtitle', sa.Text(), nullable=False, server_default='Conocé nuestros horarios, talleres especiales y la oferta de clases presenciales en nuestro espacio.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_configs', 'informative_subtitle')
    op.drop_column('home_configs', 'informative_title')
    # ### end Alembic commands ###
