"""Add courses and footer config to home_configs

Revision ID: e2dfa9a83d42
Revises: c19679b29f7e
Create Date: 2026-08-05 17:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dfa9a83d42'
down_revision: Union[str, Sequence[str], None] = 'c19679b29f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_configs', sa.Column('courses_title', sa.String(), nullable=False, server_default='NUESTROS CURSOS Y TALLERES'))
    op.add_column('home_configs', sa.Column('courses_subtitle', sa.Text(), nullable=False, server_default='Capacitaciones diseñadas para profundizar tu práctica personal y potenciar tu camino en el mundo del yoga y el bienestar.'))
    op.add_column('home_configs', sa.Column('footer_description', sa.Text(), nullable=False, server_default='Espacio dedicado a la formación profesional en yoga, meditación y bienestar consciente.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_configs', 'footer_description')
    op.drop_column('home_configs', 'courses_subtitle')
    op.drop_column('home_configs', 'courses_title')
    # ### end Alembic commands ###
