"""Add is_informative to courses

Revision ID: f7d14fa01201
Revises: e2dfa9a83d42
Create Date: 2026-08-05 17:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d14fa01201'
down_revision: Union[str, Sequence[str], None] = 'e2dfa9a83d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_informative', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_informative')
    # ### end Alembic commands ###
